// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMibcVDhsc7K3lxtFW-joHL5nX3Ld3PWI',
    appId: '1:987633027135:web:4cd849bfd22441f315508a',
    messagingSenderId: '987633027135',
    projectId: 'airport-escape',
    authDomain: 'airport-escape.firebaseapp.com',
    databaseURL: 'https://airport-escape-default-rtdb.firebaseio.com',
    storageBucket: 'airport-escape.firebasestorage.app',
    measurementId: 'G-9T1HLPB2FP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIw5e75vXhUHJ5sJANykTunDdXZLT-zE0',
    appId: '1:987633027135:android:b23a616b602c608815508a',
    messagingSenderId: '987633027135',
    projectId: 'airport-escape',
    databaseURL: 'https://airport-escape-default-rtdb.firebaseio.com',
    storageBucket: 'airport-escape.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtGrYW3j6rJoQt8bubMg-tDuC9S5sBJ-E',
    appId: '1:987633027135:ios:08ad55e9573c0d3915508a',
    messagingSenderId: '987633027135',
    projectId: 'airport-escape',
    databaseURL: 'https://airport-escape-default-rtdb.firebaseio.com',
    storageBucket: 'airport-escape.firebasestorage.app',
    iosBundleId: 'com.example.airportEscape',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtGrYW3j6rJoQt8bubMg-tDuC9S5sBJ-E',
    appId: '1:987633027135:ios:08ad55e9573c0d3915508a',
    messagingSenderId: '987633027135',
    projectId: 'airport-escape',
    databaseURL: 'https://airport-escape-default-rtdb.firebaseio.com',
    storageBucket: 'airport-escape.firebasestorage.app',
    iosBundleId: 'com.example.airportEscape',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMibcVDhsc7K3lxtFW-joHL5nX3Ld3PWI',
    appId: '1:987633027135:web:afd058208692cfbf15508a',
    messagingSenderId: '987633027135',
    projectId: 'airport-escape',
    authDomain: 'airport-escape.firebaseapp.com',
    databaseURL: 'https://airport-escape-default-rtdb.firebaseio.com',
    storageBucket: 'airport-escape.firebasestorage.app',
    measurementId: 'G-F7BJHKLBQH',
  );
}
