// Flutter app entry point and theme setup
import 'package:flutter/material.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by flutterfire configure
// Import main landing page and widgets
import 'landing_page.dart';
// Import your new layover page (needed because landing_page will use it)
import 'layover_page.dart';

// App-wide color constants
const kPrimaryColor = Color.fromARGB(255, 18, 71, 156);
const kBackgroundColor = Color(0xFFE0F7FA);

// Main function: initializes Firebase then launches the app
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // DEV ONLY: log RTDB connection status
FirebaseDatabase.instance.ref('.info/connected').onValue.listen((e) {
  // ignore: avoid_print
  print('RTDB connected: ${e.snapshot.value == true}');
});

  runApp(const MyApp());
}

// Root widget: sets up MaterialApp and theme
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Airport Escape, for passengers by passengers',
      theme: ThemeData(
        primaryColor: kPrimaryColor,
        scaffoldBackgroundColor: kBackgroundColor,
        appBarTheme: const AppBarTheme(
          backgroundColor: kPrimaryColor,
          foregroundColor: Colors.white,
        ),
      ),
      home: const MyHomePage(), // 👈 Keep the original landing page
    );
  }
}
